version: '2'
services:
    tablettop-app:
        image: tablettop
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://tablettop-postgresql:5432/TabletTop
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tablettop-postgresql:
        extends:
            file: postgresql.yml
            service: tablettop-postgresql
